// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDpJ5TdPQbNfTBbKmrxzaTW-s_YX-A7K7g',
    appId: '1:981142108015:web:57a6375be9c31f93dd5a9a',
    messagingSenderId: '981142108015',
    projectId: 'authtutorial-76044',
    authDomain: 'authtutorial-76044.firebaseapp.com',
    storageBucket: 'authtutorial-76044.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD0sFi6AwgxhVLxl9IN-AaZOhrS5bmjaXE',
    appId: '1:981142108015:android:d43693bdb0b7b03bdd5a9a',
    messagingSenderId: '981142108015',
    projectId: 'authtutorial-76044',
    storageBucket: 'authtutorial-76044.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBx-xQkSkaE41sLBa1mRh1Ko6wplBspOM4',
    appId: '1:981142108015:ios:fd3f00dc9a5b05e6dd5a9a',
    messagingSenderId: '981142108015',
    projectId: 'authtutorial-76044',
    storageBucket: 'authtutorial-76044.appspot.com',
    iosClientId: '981142108015-kuocacvvr34olkdbrc3qm5grtjfkc1jf.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBx-xQkSkaE41sLBa1mRh1Ko6wplBspOM4',
    appId: '1:981142108015:ios:7eea0fb748d599a7dd5a9a',
    messagingSenderId: '981142108015',
    projectId: 'authtutorial-76044',
    storageBucket: 'authtutorial-76044.appspot.com',
    iosClientId: '981142108015-2pc5ve4lgncvklgci406a3qn5b98do7r.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication2.RunnerTests',
  );
}
